apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scalewatch.fullname" . }}-manager-role
  labels:
  {{- include "scalewatch.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scalewatch.soh.re
  resources:
  - runnerscalesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scalewatch.soh.re
  resources:
  - runnerscalesets/finalizers
  verbs:
  - update
- apiGroups:
  - scalewatch.soh.re
  resources:
  - runnerscalesets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scalewatch.fullname" . }}-manager-rolebinding
  labels:
  {{- include "scalewatch.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "scalewatch.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "scalewatch.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'