apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scalewatch.fullname" . }}-runnerscaleset-viewer-role
  labels:
  {{- include "scalewatch.labels" . | nindent 4 }}
rules:
- apiGroups:
  - scalewatch.soh.re
  resources:
  - runnerscalesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scalewatch.soh.re
  resources:
  - runnerscalesets/status
  verbs:
  - get